version: '3.1'
services:
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./backend/db-init.js:/docker-entrypoint-initdb.d/insertData.js:ro
      - mongodbdata:/data/db
    command: mongod --bind_ip_all 
  backend:
    build: ./backend
    ports:
      - "3000:3000"
volumes:
  mongodbdata: