version: '3.1'
services:
  mongo:
    image: 'mongo'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      # MONGO_INITDB_DATABASE: rewind-test
    command: |
      mongod --bind_ip_all 
  dbinit:
    build: ./backend/db-init
    depends_on:
      - mongo
      
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - dbinit
