version: '3.8'
services:
  monogdb:
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret 
  backend:
    # image: cshewale23/rewind-backend
    build: ./backend
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - monogdb
  # ai-server:
  frontend:
    build: ./frontend
    ports:
      - 5000:5173
    env_file:
      - ./frontend/.env
      