name: Docker build and push

on:
  push:
    paths:
      - "**/Dockerfile"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Changes
        run: echo "${{toJson(github.event)}}"
    #   - name: Check
    #     run: echo "Detected ${{matrix.dockerfile}}"
    #     if: ${{ contains(github.event_path, matrix.dockerfile) }}
    # strategy:
    #   matrix:
    #     dockerfile:
    #       - ./backend/Dockerfile
    #       - ./frontend/Dockerfile
    #       - ./backend/db-init/Dockerfile

    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    # #   - name: Build and push
    #     uses: docker/build-push-action@v4
    #     with:
    #       push: true
    #       tags: chsewale23/rewind-backend:latest
    #       context: ./backend
    #       file: ./Dockerfile
